import { BlogPost, BlogCategory, BlogAuthor } from "@/types/blog";

export const mockCategories: BlogCategory[] = [
    { title: "Cybersecurity", slug: "cybersecurity" },
    { title: "TISAX®", slug: "tisax" },
    { title: "Compliance", slug: "compliance" },
    { title: "ISO 27001", slug: "iso-27001" },
    { title: "Automotive", slug: "automotive" },
];

const mockAuthorIulian: BlogAuthor = {
    name: "Iulian",
    role: "Lead Cybersecurity Architect",
    image: {
        asset: {
            url: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?q=80&w=200&auto=format&fit=crop",
        },
    },
};

export const mockPosts: BlogPost[] = [
    {
        _id: "post-1",
        title: "Understanding TISAX® AL3: A Guide to the Highest Level of Information Security in Automotive",
        slug: "understanding-tisax-al3-guide",
        publishedAt: "2026-03-01T10:00:00Z",
        excerpt: "Achieving TISAX® Assessment Level 3 is critical for suppliers handling highly confidential data. We break down the requirements, common pitfalls, and how to fast-track your compliance.",
        mainImage: { asset: { url: "https://images.unsplash.com/photo-1617814088514-6338be556d11?q=80&w=1200&auto=format&fit=crop" }, alt: "Automotive engineering and technical data" },
        author: mockAuthorIulian,
        categories: [mockCategories[1], mockCategories[4]],
        readTimeMinutes: 7,
        body: [{ _type: "block", style: "normal", children: [{ _type: "span", text: "The automotive industry demands rigorous information security." }]}],
    },
    {
        _id: "post-2",
        title: "vCISO as a Service: How Mid-Sized Tech Firms Can Bridge the Security Leadership Gap",
        slug: "vciso-as-a-service-benefits",
        publishedAt: "2026-02-28T14:30:00Z",
        excerpt: "Hiring a full-time CISO is expensive and challenging. Discover how a virtual Chief Information Security Officer (vCISO) provides enterprise-grade strategic direction at a fraction of the cost.",
        mainImage: { asset: { url: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=800&auto=format&fit=crop" }, alt: "Server room networking equipment" },
        author: mockAuthorIulian,
        categories: [mockCategories[0]],
        readTimeMinutes: 5,
        body: [{ _type: "block", style: "normal", children: [{ _type: "span", text: "A vCISO brings immediate leadership." }]}],
    },
    {
        _id: "post-3",
        title: "ISO 27001:2022 Transition Toolkit: Updating Your ISMS Before the Deadline",
        slug: "iso-27001-2022-transition-toolkit",
        publishedAt: "2026-02-20T09:15:00Z",
        excerpt: "The deadline for transitioning to the new ISO/IEC 27001:2022 standard is looming. Here is your definitive checklist to ensure your Information Security Management System (ISMS) complies with the updated Annex A controls.",
        mainImage: { asset: { url: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=800&auto=format&fit=crop" }, alt: "Business team reviewing documents" },
        author: mockAuthorIulian,
        categories: [mockCategories[3], mockCategories[2]],
        readTimeMinutes: 8,
        body: [{ _type: "block", style: "normal", children: [{ _type: "span", text: "The new standard is here to stay." }]}],
    },
    {
        _id: "post-4",
        title: "The Anatomy of a Modern Penetration Test: Beyond Automated Scans",
        slug: "anatomy-modern-penetration-test",
        publishedAt: "2026-02-15T11:45:00Z",
        excerpt: "Running Nessus is not a penetration test. We explore the critical differences between vulnerability scanning and manual, objective-based ethical hacking, and why your compliance auditors demand the latter.",
        mainImage: { asset: { url: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?q=80&w=800&auto=format&fit=crop" }, alt: "Hacker screen" },
        author: mockAuthorIulian,
        categories: [mockCategories[0]],
        readTimeMinutes: 6,
        body: [{ _type: "block", style: "normal", children: [{ _type: "span", text: "Penetration testing is an art." }]}],
    },
    {
        _id: "post-5",
        title: "Navigating the NIS2 Directive: Is Your Supply Chain Ready?",
        slug: "navigating-nis2-directive-supply-chain",
        publishedAt: "2026-02-10T08:00:00Z",
        excerpt: "The European NIS2 directive explicitly places responsibility on management to secure the entire software supply chain. Find out if your third-party vendors are putting your compliance status at risk.",
        mainImage: { asset: { url: "https://images.unsplash.com/photo-1586528116311-ad8ed7c8260b?q=80&w=800&auto=format&fit=crop" }, alt: "Logistics and supply chain" },
        author: mockAuthorIulian,
        categories: [mockCategories[2], mockCategories[0]],
        readTimeMinutes: 10,
        body: [{ _type: "block", style: "normal", children: [{ _type: "span", text: "Supply chain attacks are rising." }]}],
    },
    {
        _id: "post-6",
        title: "Building a Cyber-Resilient Culture: Effective Security Awareness Training",
        slug: "building-cyber-resilient-culture",
        publishedAt: "2026-01-28T09:30:00Z",
        excerpt: "Phishing remains the number one initial access vector for ransomware operators. Discover how gamified, ongoing Security Awareness Training drastically reduces your organization's human attack surface.",
        mainImage: { asset: { url: "https://images.unsplash.com/photo-1516321497487-e288fb19713f?q=80&w=800&auto=format&fit=crop" }, alt: "Team working together" },
        author: mockAuthorIulian,
        categories: [mockCategories[0]],
        readTimeMinutes: 5,
        body: [{ _type: "block", style: "normal", children: [{ _type: "span", text: "Your employees are your first line of defense." }]}],
    },
    {
        _id: "post-7",
        title: "TISAX® vs. ISO 27001: Which Certification Does Your Business Actually Need?",
        slug: "tisax-vs-iso-27001-comparison",
        publishedAt: "2026-01-22T14:00:00Z",
        excerpt: "While TISAX® is derived from ISO 27001, the assessment methodology and industry acceptance differ fundamentally. We compare the two frameworks to help you decide your strategic compliance roadmap.",
        mainImage: { asset: { url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=800&auto=format&fit=crop" }, alt: "Data analytics charts" },
        author: mockAuthorIulian,
        categories: [mockCategories[1], mockCategories[3], mockCategories[2]],
        readTimeMinutes: 9,
        body: [{ _type: "block", style: "normal", children: [{ _type: "span", text: "Choosing the right framework dictates your security posture." }]}],
    },
    {
        _id: "post-8",
        title: "Zero-Trust Architecture on a Hybrid Cloud: A Practical Implementation Guide",
        slug: "zero-trust-architecture-hybrid-cloud",
        publishedAt: "2026-01-15T11:00:00Z",
        excerpt: "Moving from perimeter-based security to a Zero-Trust framework is complex. Learn how our architects maintain workforce productivity while locking down distributed Azure and AWS environments.",
        mainImage: { asset: { url: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800&auto=format&fit=crop" }, alt: "Abstract cloud network graphic" },
        author: mockAuthorIulian,
        categories: [mockCategories[0]],
        readTimeMinutes: 11,
        body: [{ _type: "block", style: "normal", children: [{ _type: "span", text: "Never trust, always verify." }]}],
    },
    {
        _id: "post-9",
        title: "DORA: The Digital Operational Resilience Act Explained",
        slug: "dora-digital-operational-resilience-act",
        publishedAt: "2026-01-08T15:20:00Z",
        excerpt: "The EU's DORA regulation establishes strict requirements for financial entities and their ICT service providers. Learn how to map your current ISMS controls to DORA requirements.",
        mainImage: { asset: { url: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=80&w=800&auto=format&fit=crop" }, alt: "Abstract technology blocks" },
        author: mockAuthorIulian,
        categories: [mockCategories[2]],
        readTimeMinutes: 7,
        body: [{ _type: "block", style: "normal", children: [{ _type: "span", text: "Financial resilience is now codified in law." }]}],
    },
    {
        _id: "post-10",
        title: "Automotive Cybersecurity: Integrating ISO/SAE 21434 with TISAX®",
        slug: "automotive-cybersecurity-iso-21434-tisax",
        publishedAt: "2025-12-28T09:00:00Z",
        excerpt: "While TISAX® protects organizational data, ISO/SAE 21434 secures the vehicle itself. Learn how to harmonize these two critical automotive standards for a holistic cybersecurity strategy.",
        mainImage: { asset: { url: "https://images.unsplash.com/photo-1503378415752-9f37ff86af80?q=80&w=800&auto=format&fit=crop" }, alt: "Modern automotive interior" },
        author: mockAuthorIulian,
        categories: [mockCategories[4], mockCategories[1]],
        readTimeMinutes: 8,
        body: [{ _type: "block", style: "normal", children: [{ _type: "span", text: "Secure by design, from the factory to the road." }]}],
    },
    {
        _id: "post-11",
        title: "Cloud Security Posture Management (CSPM): Finding the Misconfigurations Before Hackers Do",
        slug: "cspm-finding-misconfigurations",
        publishedAt: "2025-12-15T13:45:00Z",
        excerpt: "Up to 80% of cloud breaches occur due to customer misconfiguration. We explore how continuous CSPM tools integrate with your ISMS to automatically remediate vulnerable S3 buckets and exposed APIs.",
        mainImage: { asset: { url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=800&auto=format&fit=crop" }, alt: "Global network connectivity" },
        author: mockAuthorIulian,
        categories: [mockCategories[0]],
        readTimeMinutes: 6,
        body: [{ _type: "block", style: "normal", children: [{ _type: "span", text: "Visibility is the first step in cloud security." }]}],
    },
    {
        _id: "post-12",
        title: "Incident Response Playbooks: Why You Need Them Before a Breach",
        slug: "incident-response-playbooks-importance",
        publishedAt: "2025-12-05T10:30:00Z",
        excerpt: "When ransomware strikes, every minute counts. Discover how developing and testing targeted Incident Response Playbooks (IRPs) can save your organization millions in downtime and reputational damage.",
        mainImage: { asset: { url: "https://images.unsplash.com/photo-1614064641913-6b7140414c71?q=80&w=800&auto=format&fit=crop" }, alt: "Emergency response" },
        author: mockAuthorIulian,
        categories: [mockCategories[0]],
        readTimeMinutes: 5,
        body: [{ _type: "block", style: "normal", children: [{ _type: "span", text: "Preparation prevents panic." }]}],
    },
    {
        _id: "post-13",
        title: "Deciphering Internal vs. External Audits for ISO 27001",
        slug: "internal-vs-external-audits-iso-27001",
        publishedAt: "2025-11-20T14:15:00Z",
        excerpt: "What is the difference between a Stage 1 and Stage 2 external audit? And why is a rigorous internal audit your best defense against non-conformities? We break down the ISO 27001 audit lifecycle.",
        mainImage: { asset: { url: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=800&auto=format&fit=crop" }, alt: "Accounting and auditing charts" },
        author: mockAuthorIulian,
        categories: [mockCategories[3], mockCategories[2]],
        readTimeMinutes: 7,
        body: [{ _type: "block", style: "normal", children: [{ _type: "span", text: "Audits measure the pulse of your ISMS." }]}],
    },
    {
        _id: "post-14",
        title: "Social Engineering Assessments: Testing the Human Element",
        slug: "social-engineering-assessments",
        publishedAt: "2025-11-10T09:45:00Z",
        excerpt: "Firewalls can't patch human trust. We recount real-world scenarios where authorized phishing, vishing, and physical tailgating exercises exposed critical security gaps during our red-team engagements.",
        mainImage: { asset: { url: "https://images.unsplash.com/photo-1573164713988-8665fc963095?q=80&w=800&auto=format&fit=crop" }, alt: "Person looking at phone in the dark" },
        author: mockAuthorIulian,
        categories: [mockCategories[0]],
        readTimeMinutes: 8,
        body: [{ _type: "block", style: "normal", children: [{ _type: "span", text: "Trust but verify." }]}],
    },
    {
        _id: "post-15",
        title: "How to Build a Vendor Risk Management (VRM) Program from Scratch",
        slug: "building-vendor-risk-management-program",
        publishedAt: "2025-10-25T11:20:00Z",
        excerpt: "Outsourcing services doesn't mean outsourcing risk. Learn how to establish a robust VRM framework to continuously assess, monitor, and audit your critical third-party suppliers.",
        mainImage: { asset: { url: "https://images.unsplash.com/photo-1556761175-5973dc0f32b7?q=80&w=800&auto=format&fit=crop" }, alt: "Business people shaking hands" },
        author: mockAuthorIulian,
        categories: [mockCategories[2], mockCategories[0]],
        readTimeMinutes: 9,
        body: [{ _type: "block", style: "normal", children: [{ _type: "span", text: "Your security is only as strong as your weakest vendor." }]}],
    }
];
